### ISSUE TITLE
ALPINE_GLIBC_BASE_URL is broken

### ISSUE THREAD

**Issue by duytruong** [rawmind0/alpine-jvm8#3]
Hi @rawmind0 

ALPINE_GLIBC_BASE_URL="https://github.com/andyshinn/alpine-pkg-glibc/releases/download" is broken. Can we use https://github.com/sgerrand/alpine-pkg-glibc instead?

**Comment by rawmind0** [comment]
Hi @duytruong ... thanks so much for the advise.... :)

Updated glibc package to sgerrnad v 2.25-r0 and jre version to 1.8.144 in last commit, https://github.com/rawmind0/alpine-jvm8/commit/e862d9efe5dfd6c029ff7ee75f9fbbd110c3a4ab
